language: elixir

elixir:
  - 1.1.0

otp_release:
  - 18.1

env: MIX_ENV=test

sudo: false # faster builds

notifications:
  email: false

before_script:
  - gem install bundler
  - bundle install

before_install:
  - rvm install 2.2

script:
  - mix test
  - mix dogma
  - jekyll build
